### ISSUE TITLE
Make checker :command configurable

### ISSUE THREAD

**Issue by kritzcreek** [bsermons/flycheck-purescript#3]
https://github.com/bsermons/flycheck-purescript/blob/b1c473630c1221e0ffa4084757403b0cf622b1fa/flycheck-purescript.el#L99-L105

Some people might have their sources in different directories or maybe already have set up a command with npm scripts, make, gulp. ... whatever.

**Comment by bsermons** [comment]
Ok, I made the psc options customizable.  I'm open as to what the default glob patterns or options should be but what is there now should work for the default pulp project setup.  That is all I've used so let me know if you have a better suggestion.

**Comment by kritzcreek** [comment]
great thanks! Let's roll with this for now. If someone has more specific needs we can still customize more.
